import { Injectable, signal } from '@angular/core';

export type Lang = 'vi' | 'en';

@Injectable({ providedIn: 'root' })
export class UiService {
  currentLang = signal<Lang>((localStorage.getItem('ui_lang') as Lang) ?? 'en');

  private dict: Record<Lang, Record<string, string>> = {
    vi: {
      'nav.home': 'Trang chủ',
      'nav.createTask': 'Tạo Task',
      'nav.dashboard': 'Workload Dashboard',
      'nav.kanban': 'Kanban Board',
      'nav.update': 'Cập nhật Task',
      'btn.create': 'Tạo',
      'btn.update': 'Cập nhật',
      'btn.loadData': 'Tải dữ liệu',
      'label.title': 'Tiêu đề',
      'label.description': 'Mô tả',
      'label.departmentId': 'ID Phòng ban',
      'label.assigneeId': 'ID Người phụ trách',
      'label.dueDate': 'Due Date',
      'label.priority': 'Priority',
      'label.supervisors': 'Supervisor IDs (comma separated)',
      'task.dueDate': 'Hạn chót',
      'task.priority': 'Độ ưu tiên',
      'task.supervisors': 'Người giám sát (Supervisor)',
      'task.createBtn': 'Tạo Task',
      'task.ph.title': 'Nhập tiêu đề...',
      'task.ph.desc': 'Nhập mô tả công việc...',
      'task.ph.dept': 'Chọn hoặc nhập ID phòng ban',
      'task.ph.assignee': 'Chọn hoặc nhập ID người phụ trách',
      'task.ph.supervisors': 'VD: id1, id2',
      'placeholder.searchDept': 'Nhập ID phòng ban',
      'placeholder.searchUser': 'Nhập ID người dùng',
      'creating': 'Đang tạo task...',
      'updating': 'Đang cập nhật...',
      'kanban.todo': 'Cần làm',
      'kanban.inProgress': 'Đang làm',
      'kanban.completed': 'Đã hoàn thành',
      'kanban.cancelled': 'Đã hủy',
      'kanban.empty': 'Chưa có công việc nào',
      'kanban.searchPlaceholder': 'Tìm kiếm task...',
      'kanban.highPriority': 'Ưu tiên cao',
      'kanban.overdue': 'Quá hạn',
      'modal.title': 'Chi tiết Task',
      'modal.save': 'Lưu thay đổi',
      'modal.close': 'Đóng',
      'tasklist.title': 'Danh sách Task',
      'tasklist.select': 'Chọn một task để thảo luận',
      'kpi.view': 'Xem KPI Phòng Ban',
      'loading.tasks': 'Đang tải danh sách công việc...',
      'summarize': 'Tóm tắt',
      'composer.placeholder': 'Gõ tin nhắn...',
      'empty.chat': 'Chưa có dữ liệu chat cho công việc này.',
      'bot.thinking': 'Bot đang suy nghĩ...',
      'chooseTaskLeft': 'Chọn một công việc ở cột trái để thao tác.',
      'kpi.title': 'KPI Phòng',
      'kpi.total': 'Tổng Task',
      'kpi.completed': 'Hoàn thành',
      'kpi.inProgress': 'Đang làm',
      'kpi.rate': 'Tỷ lệ',
      'dashboard.overdueTasks': 'Các Task Quá Hạn',
      'dashboard.noOverdue': 'Không có Task nào bị trễ.',
      'dashboard.workloadSummary': 'Tổng hợp Workload',
      'dashboard.noWorkload': 'Chưa có dữ liệu Workload.',
      'dashboard.searchDept': 'Tìm theo Department ID',
      'dashboard.searchUser': 'Tìm theo User ID',
      'dashboard.loadBtn': 'Tải Dữ Liệu',
      'dashboard.col.user': 'Người dùng',
      'dashboard.col.total': 'Tổng',
      'dashboard.col.completed': 'Hoàn thành',
      'dashboard.col.inProgress': 'Đang làm',
      'dashboard.col.overdue': 'Quá hạn',
      'dashboard.col.rate': 'Tỷ lệ hoàn thành',
      'loading.general': 'Đang tải...',
      'title.updateTask': 'Cập nhật Trạng thái Task',
      'label.taskId': 'Nhập Task ID',
      'label.status': 'Trạng thái',
      'btn.updateStatus': 'Cập nhật'
    },
    en: {
      'nav.home': 'Home',
      'nav.createTask': 'Create Task',
      'nav.dashboard': 'Workload Dashboard',
      'nav.kanban': 'Kanban Board',
      'nav.update': 'Update Task',
      'btn.create': 'Create',
      'btn.update': 'Update',
      'btn.loadData': 'Load Data',
      'label.title': 'Title',
      'label.description': 'Description',
      'label.departmentId': 'Department ID',
      'label.assigneeId': 'Assignee ID',
      'label.dueDate': 'Due Date',
      'label.priority': 'Priority',
      'label.supervisors': 'Supervisor IDs (comma separated)',
      'task.dueDate': 'Due Date',
      'task.priority': 'Priority',
      'task.supervisors': 'Supervisor IDs (comma separated)',
      'task.createBtn': 'Create Task',
      'task.ph.title': 'Enter title...',
      'task.ph.desc': 'Enter description...',
      'task.ph.dept': 'Enter Department ID',
      'task.ph.assignee': 'Enter Assignee ID',
      'task.ph.supervisors': 'e.g., id1, id2',
      'placeholder.searchDept': 'Enter department ID',
      'placeholder.searchUser': 'Enter user ID',
      'creating': 'Creating task...',
      'updating': 'Updating...',
      'kanban.todo': 'To Do',
      'kanban.inProgress': 'In Progress',
      'kanban.completed': 'Completed',
      'kanban.cancelled': 'Cancelled',
      'kanban.empty': 'No tasks',
      'kanban.searchPlaceholder': 'Search tasks...',
      'kanban.highPriority': 'High Priority',
      'kanban.overdue': 'Overdue',
      'modal.title': 'Task Details',
      'modal.save': 'Save Changes',
      'modal.close': 'Close',
      'tasklist.title': 'Task List',
      'tasklist.select': 'Select a task to discuss',
      'kpi.view': 'View Department KPI',
      'loading.tasks': 'Loading task list...',
      'summarize': 'Summarize',
      'composer.placeholder': 'Type your message here...',
      'empty.chat': 'No chat data for this task.',
      'bot.thinking': 'Bot is thinking...',
      'chooseTaskLeft': 'Select a task on the left to interact.',
      'kpi.title': 'Department KPI',
      'kpi.total': 'Total Tasks',
      'kpi.completed': 'Completed',
      'kpi.inProgress': 'In Progress',
      'kpi.rate': 'Rate',
      'dashboard.overdueTasks': 'Overdue Tasks',
      'dashboard.noOverdue': 'No overdue tasks found.',
      'dashboard.workloadSummary': 'Workload Summary',
      'dashboard.noWorkload': 'No workload data.',
      'dashboard.searchDept': 'Enter department ID',
      'dashboard.searchUser': 'Enter user ID',
      'dashboard.loadBtn': 'Load Data',
      'dashboard.col.user': 'User',
      'dashboard.col.total': 'Total',
      'dashboard.col.completed': 'Completed',
      'dashboard.col.inProgress': 'In Progress',
      'dashboard.col.overdue': 'Overdue',
      'dashboard.col.rate': 'Completion Rate',
      'loading.general': 'Loading...',
      'title.updateTask': 'Update Task Status',
      'label.taskId': 'Enter Task ID',
      'label.status': 'Status',
      'btn.updateStatus': 'Update'
    }
  };

  setLanguage(lang: Lang): void {
    this.currentLang.set(lang);
    try { localStorage.setItem('ui_lang', lang); } catch { }
  }

  translate(key: string): string {
    const lang = this.currentLang();
    return this.dict[lang]?.[key] ?? key;
  }
}
